[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E203", "E266"]

[tool.mypy]
python_version = "3.11"
strict = false
ignore_missing_imports = true
show_error_codes = true
